### ISSUE TITLE
Reaching out 

### ISSUE THREAD

**Issue by Abdulaziz-almoshen** [takoyakikun/laravel_nuxt_spa_login#7]
Hello there
Your repo on Nuxt is great!! I would like to contact you regarding a job offer. What's the appropriate way?

**Comment by takoyakikun** [comment]
Thank you for your great evaluation.

**Comment by Abdulaziz-almoshen** [comment]
Can I get your WhatsApp number?

**Comment by takoyakikun** [comment]
I got WhatsApp number.

**Comment by Abdulaziz-almoshen** [comment]
Can you share with me at 
Abdulazizalmohsen92@gmail.com
